name: CI

on:
  push:
    branches:
      - misc_improvements
  pull_request:
    branches:
      - main
      - misc_improvements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --exit-zero

      - name: Run unit tests
        run: |
       PYTHONPATH=$GITHUB_WORKSPACE python -m unittest discover -s tests -p 'test_*.py'
